// react-next/src/app/-/stops/page.tsx
"use client";

import { StopCard } from "@/components/StopCard";
import { getStopsQuery } from "@/lib/queries";
import { useQuery } from "@tanstack/react-query";

export default function Page() {
  const stopsQuery = useQuery(getStopsQuery);

  if (stopsQuery.isLoading || !stopsQuery.data) {
    return <div>Loading...</div>;
  }

  if (stopsQuery.isError) {
    return <div>Error: {stopsQuery.error.message}</div>;
  }

  return (
    <div className="flex max-h-full flex-wrap space-y-2 overflow-y-scroll">
      {stopsQuery.data.stop.map((stop) => (
        <StopCard key={stop.stopID} stopData={stop} />
      ))}
    </div>
  );
}

// front/src/routes/-/stops/+page.svelte
<script lang="ts">
	import Stop from '$lib/components/bus/stop.svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import { getStops } from 'peaktransit';
	const stopsQuery = createQuery({
		queryKey: ['stops'],
		queryFn: getStops
	});
</script>

{#if $stopsQuery.isPending}
	Loading...
{/if}
{#if $stopsQuery.error}
	An error has occurred:
	{$stopsQuery.error.message}
{/if}
{#if $stopsQuery.isSuccess}
	<div class="flex flex-wrap space-x-2 space-y-2">
		{#each $stopsQuery.data.stop as stop}
			<Stop bind:stopData={stop} />
		{/each}
	</div>
{/if}
