// svelte-kit/src/lib/components/bus/StopMap.svelte
<script lang="ts">
	import { Map, Marker, TileLayer } from 'sveaflet';
	import { createQuery } from '@tanstack/svelte-query';
	import { getStops } from 'peaktransit';
	import TestMarker from './TestMarker.svelte';
	const stopsQuery = createQuery({
		queryKey: ['stops'],
		queryFn: getStops
	});
</script>

<Map options={{ center: [44.47772, -73.1945], zoom: 16 }}>
	<TileLayer
		url={'https://tile.openstreetmap.org/{z}/{x}/{y}.png'}
		options={{
			maxZoom: 24,
			attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
		}}
	/>
	{#if $stopsQuery.isSuccess}
		{#each $stopsQuery.data.stop as stop}
			<Marker latLng={[stop.lat, stop.lng]} />
			<TestMarker bind:stopData={stop} />
		{/each}
	{/if}
	<slot></slot>
</Map>

// react-next/src/app/stops/@stopMap/StopMap.tsx
"use client";
import { getStopsQuery } from "@/lib/queries";
import { useQuery } from "@tanstack/react-query";
import type { Stop } from "peaktransit";
import { MapContainer, Marker, Popup, TileLayer, useMap } from "react-leaflet";
import { useParams } from "next/navigation";
import { useEffect, useMemo } from "react";
import type { LatLngExpression } from "leaflet";

const DEFAULT_POSITION = [44.47522, -73.19255] as LatLngExpression;
const DEFAULT_ZOOM = 15 as const;

export function StopMap() {
  const stopsQuery = useQuery(getStopsQuery);
  const { stopId } = useParams<{ stopId: string }>();

  const selectedStop = useMemo(() => {
    return stopsQuery.data?.stop.find(
      (stop) => stop.stopID.toString() === stopId
    );
  }, [stopsQuery.data, stopId]);

  return (
    <MapContainer
      className="w-full h-full rounded-xl"
      center={DEFAULT_POSITION}
      zoom={DEFAULT_ZOOM}
      scrollWheelZoom={true}
      minZoom={15}
    >
      <TileLayer
        url={"https://tile.openstreetmap.org/{z}/{x}/{y}.png"}
        attribution='&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
      />
      {stopsQuery.data?.stop.map((stop) => (
        <StopMarker
          key={stop.stopID}
          stopData={stop}
          selected={selectedStop?.stopID === stop.stopID}
        />
      ))}
      <StopWatcher />
    </MapContainer>
  );
}

function StopMarker({
  stopData,
  selected,
}: {
  stopData: Stop;
  selected: boolean;
}) {
  return (
    <Marker position={[stopData.lat, stopData.lng]}>
      <Popup className="bg-red-300">{stopData.longName}</Popup>
    </Marker>
  );
}

// This component uses the map hooks to zoom into/out of a stop whenever a stop is selected or deselected.
function StopWatcher() {
  const map = useMap();
  const { stopId } = useParams<{ stopId: string }>();

  const stopsQuery = useQuery(getStopsQuery);

  const selectedStop = useMemo(() => {
    return stopsQuery.data?.stop.find(
      (stop) => stop.stopID.toString() === stopId
    );
  }, [stopsQuery.data, stopId]);

  useEffect(() => {
    if (selectedStop !== undefined) {
      map.flyTo([selectedStop.lat, selectedStop.lng], 18);
    } else {
      map.flyTo(DEFAULT_POSITION, DEFAULT_ZOOM);
    }
  }, [selectedStop, map]);

  return null;
}
