// svelte-kit/src/lib/components/bus/StopMap.svelte
<script lang="ts">
	import { Map, Marker, TileLayer } from 'sveaflet';
	import { createQuery } from '@tanstack/svelte-query';
	import { getStops } from 'peaktransit';
	import TestMarker from './TestMarker.svelte';
	const stopsQuery = createQuery({
		queryKey: ['stops'],
		queryFn: getStops
	});
</script>

<Map options={{ center: [44.47772, -73.1945], zoom: 16 }}>
	<TileLayer
		url={'https://tile.openstreetmap.org/{z}/{x}/{y}.png'}
		options={{
			maxZoom: 24,
			attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
		}}
	/>
	{#if $stopsQuery.isSuccess}
		{#each $stopsQuery.data.stop as stop}
			<Marker latLng={[stop.lat, stop.lng]} />
			<TestMarker bind:stopData={stop} />
		{/each}
	{/if}
	<slot></slot>
</Map>

// react-next/src/components/StopMap.tsx
"use client";
import { getStopsQuery } from "@/lib/queries";
import { useQuery } from "@tanstack/react-query";
import { Stop } from "peaktransit";
import { MapContainer, Marker, Popup, TileLayer } from "react-leaflet";

export function StopMap() {
  const stopsQuery = useQuery(getStopsQuery);
  return (
    <MapContainer
      className="w-full h-full"
      center={[44.47522, -73.19255]}
      zoom={15}
      scrollWheelZoom={true}
    >
      <TileLayer
        url={"https://tile.openstreetmap.org/{z}/{x}/{y}.png"}
        attribution='&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
      />
      {stopsQuery.data?.stop.map((stop) => (
        <StopMarker key={stop.stopID} stopData={stop} />
      ))}
    </MapContainer>
  );
}

function StopMarker({ stopData }: { stopData: Stop }) {
  return (
    <Marker position={[stopData.lat, stopData.lng]}>
      <Popup>{stopData.longName}</Popup>
    </Marker>
  );
}
