// react-next/src/components/StopCard.tsx
import { Stop } from "peaktransit";
import { Card, CardTitle, CardHeader, CardContent } from "./ui/card";

export function StopCard({ stopData }: { stopData: Stop }) {
  return (
    <Card className="basis-full shrink-0 grow-1">
      <CardHeader>
        <CardTitle>{stopData.longName}</CardTitle>
      </CardHeader>
      <CardContent></CardContent>
    </Card>
  );
}

// front/src/lib/components/bus/StopCard.svelte
<script lang="ts">
	import { type Stop } from 'peaktransit';
	export let stopData: Stop;

	import * as Card from '$lib/components/ui/card/index.js';
</script>

<Card.Root class=" basis-full shrink-0 grow-1">
	<Card.Header>
		<Card.Title>{stopData.longName}</Card.Title>
	</Card.Header>
	<Card.Content></Card.Content>
</Card.Root>
